import { ui,esc,tr,locale,fmtClock } from './model.js';

export function filesHtml(){const groups=ui.dashboard.sessions.map((session)=>({session,items:session.artifacts||[]})).filter((g)=>g.items.length);if(!groups.length)return `<section class="empty-state"><div class="glyph">⇩</div><h3>${esc(tr('noFiles'))}</h3><p>Vigilume chỉ hiện artifact khi có DOM/network/download evidence đủ mạnh.</p></section>`;return groups.map(({session,items})=>{const files=items.filter((x)=>x.kind==='file');return `<div class="section-head"><div><h2>${esc(session.title||`Tab ${session.tabId}`)}</h2><p>${files.length} file · ${items.length-files.length} reference</p></div>${files.length?`<button class="small-button" data-action="download-all" data-tab="${session.tabId}">${esc(tr('downloadAll'))}</button>`:''}</div><section class="artifact-list">${items.map((a)=>`<article class="artifact-card"><div class="artifact-icon">${esc((a.family||a.kind||'FILE').slice(0,4).toUpperCase())}</div><div class="artifact-meta"><strong>${esc(a.name||a.href||'Artifact')}</strong><span>${esc(a.source||'observed')}${a.downloadState?` · ${esc(a.downloadState)}`:''}</span></div>${a.kind==='file'?`<button data-action="download" data-tab="${session.tabId}" data-artifact="${esc(a.artifactId)}">${esc(tr('download'))}</button>`:`<button data-action="open-artifact" data-href="${esc(a.href||'')}">Mở</button>`}</article>`).join('')}</section>`;}).join('');}

export function automationHtml(){
  const rules=ui.dashboard.automationRules||[],queue=ui.dashboard.queuedActions||[],sessions=ui.dashboard.sessions||[];
  const engineOn=Boolean(ui.dashboard.settings?.automationsEnabled&&!ui.dashboard.settings?.automationPaused);
  const tabOptions=sessions.map((s)=>`<option value="${Number(s.tabId)}">Tab ${Number(s.tabId)} · ${esc(s.title||'ChatGPT')} · ${esc(s.state||'')}</option>`).join('');
  const ruleRows=rules.map((r)=>{
    const trigger=r.trigger==='time'?`Đúng ${esc(new Date(Number(r.runAt)||0).toLocaleString())}`:`${esc(r.whenState||'COMPLETED')} + ${Math.round(Number(r.delayMs||0)/1000)}s`;
    const target=r.tabId?`Tab ${Number(r.tabId)}`:'mọi tab';
    return `<article class="rule-card"><div class="rule-info"><strong>${esc(r.name||r.id)}</strong><p>${target} · ${trigger} → ${esc(r.action?.type||'action')} · ${Number(r.runCount||0)}/${Number(r.maxRuns||'∞')}</p></div><button class="switch ${r.enabled?'on':''}" data-action="toggle-rule" data-rule="${esc(r.id)}" data-enabled="${r.enabled?'1':'0'}"></button></article>`;
  }).join('');
  return `<section class="settings-card"><div class="setting-row"><div class="setting-copy"><strong>Automation engine</strong><span>${engineOn?'ĐANG BẬT — rule có thể tự gửi prompt':'ĐANG TẮT — rule chỉ được lưu, không thực thi'}</span></div><span class="evidence-chip">${engineOn?'ON':'OFF'}</span></div></section>
  <div class="section-head"><div><h2>Safe Prompt Queue</h2><p>${queue.length} durable item</p></div></div>${queue.length?`<section class="rule-list">${queue.map((item)=>`<article class="rule-card"><div class="rule-info"><strong>${esc((item.text||'').slice(0,90))}</strong><p>Tab ${item.tabId} · ${esc(item.status||'queued')} · hết hạn ${esc(fmtClock(item.expiresAt))}</p></div><button class="small-button" data-action="cancel-queue" data-queue="${esc(item.id)}">${esc(tr('cancel'))}</button></article>`).join('')}</section>`:`<div class="empty-state"><p>${esc(tr('noQueue'))}</p></div>`}
  <div class="section-head"><div><h2>Automation rules</h2><p>Rule được khóa theo tab để tránh gửi nhầm conversation.</p></div></div><section class="rule-list">${ruleRows||'<div class="empty-state"><p>Chưa có rule.</p></div>'}</section>
  <div class="section-head"><div><h2>${esc(tr('newRule'))}</h2><p>Tự gửi sau state hoặc đúng một thời điểm cụ thể.</p></div></div><section class="settings-card"><div class="form-grid">
    <div class="field"><label>ChatGPT đích</label><select id="ruleTab"><option value="">Chọn tab…</option>${tabOptions}</select></div>
    <div class="field"><label>Kiểu trigger</label><select id="ruleTrigger"><option value="state">Sau khi thấy state</option><option value="time">Đúng thời gian</option></select></div>
    <div class="field"><label>State (dùng khi trigger = state)</label><select id="ruleState"><option>COMPLETED</option><option>IDLE</option><option>CONNECTION_LOST</option><option>STALLED</option><option>CONVERSATION_LIMIT</option></select></div>
    <div class="field"><label>Thời gian (dùng khi trigger = time)</label><input id="ruleRunAt" type="datetime-local"></div>
    <div class="field"><label>Prompt</label><textarea id="rulePrompt" rows="4" placeholder="Tiếp tục hoàn thành đi nhé"></textarea></div>
    <div class="inline-fields"><div class="field"><label>Delay sau state (giây)</label><input id="ruleDelay" type="number" min="0" value="1"></div><div class="field"><label>Max runs</label><input id="ruleMaxRuns" type="number" min="1" value="1"></div></div>
    <label class="scope"><input id="ruleEnableEngine" type="checkbox" checked>Bật Automation engine sau khi lưu</label>
    <button class="small-button" data-action="create-rule" ${sessions.length?'':'disabled'}>${esc(tr('save'))}</button>
  </div></section>`;
}

export function bridgeHtml(){const bridge=ui.dashboard.bridge||{},scopes=ui.dashboard.settings?.agentScopes||[],all=['observe','open','compose','send','stop','retry','download','context_read','context_delete','automation_write'];return `<section class="bridge-card"><div class="setting-row"><div class="setting-copy"><strong>${esc(tr('bridge'))}</strong><span>${bridge.connected?esc(tr('connected')):esc(tr('disconnected'))}</span></div><button class="switch ${ui.dashboard.settings?.bridgeEnabled?'on':''}" data-action="toggle-bridge"></button></div><div class="bridge-endpoint">Native Messaging: com.vigilume.bridge<br>HTTP/MCP: 127.0.0.1:17892</div><div class="warning-note">Bridge mặc định tắt. Companion chỉ bind loopback và yêu cầu bearer token.</div></section><div class="section-head"><div><h2>Agent capability scopes</h2><p>Cấp quyền theo hành động, không có god mode.</p></div></div><section class="bridge-card"><div class="scope-grid">${all.map((s)=>`<label class="scope"><input type="checkbox" data-scope="${s}" ${scopes.includes(s)?'checked':''}>${s}</label>`).join('')}</div></section>`;}
export function settingsHtml(){const s=ui.dashboard.settings||{},toggle=(key,label,desc,value)=>`<div class="setting-row"><div class="setting-copy"><strong>${esc(label)}</strong><span>${esc(desc)}</span></div><button class="switch ${value?'on':''}" data-action="setting-toggle" data-key="${key}"></button></div>`;return `<section class="settings-card">${toggle('deepObserve',tr('deep'),'DOM + CDP Network/Runtime/Performance.',s.deepObserve)}${toggle('automationsEnabled',tr('automation'),'Cho phép rule đã bật được thực thi.',s.automationsEnabled)}${toggle('recovery.enabled',tr('recovery'),'Retry có guard + exponential backoff.',s.recovery?.enabled)}${toggle('handoff.enabled',tr('handoff'),'Mở chat mới và mang Context Vault sang.',s.handoff?.enabled)}${toggle('watchdog.enabled',tr('watchdog'),'Re-discover tab, reattach CDP và dọn context.',s.watchdog?.enabled)}</section><section class="settings-card"><div class="field"><label>${esc(tr('language'))}</label><select id="languageSelect"><option value="vi" ${locale()==='vi'?'selected':''}>Tiếng Việt</option><option value="en" ${locale()==='en'?'selected':''}>English</option></select></div><div class="field" style="margin-top:9px"><label>${esc(tr('retention'))}</label><select id="retentionMode"><option value="full" ${s.retentionMode==='full'?'selected':''}>${esc(tr('full'))}</option><option value="telemetry" ${s.retentionMode==='telemetry'?'selected':''}>${esc(tr('telemetry'))}</option><option value="off" ${s.retentionMode==='off'?'selected':''}>${esc(tr('off'))}</option></select></div><div class="field" style="margin-top:9px"><label>Retention days</label><select id="retentionDays">${[1,7,30,90].map((n)=>`<option value="${n}" ${Number(s.retentionDays)===n?'selected':''}>${n}</option>`).join('')}</select></div></section>`;}
