export const ui={view:'overview',dashboard:{sessions:[],settings:{},automationRules:[],queuedActions:[],bridge:{},tasks:[]},selectedTabId:null,selectedTaskId:null,taskDetail:null,taskRecovery:null,context:null,diagnostic:null,loading:false,lastRefreshAt:0};

const T={
  vi:{controlRoom:'Phòng điều khiển ChatGPT',openNew:'Mở ChatGPT mới',overview:'Tổng quan',tasks:'Công việc',files:'Tệp',automation:'Tự động hóa',agentPort:'Cổng AI',settings:'Cài đặt',sessions:'Phiên',working:'Đang làm',completed:'Hoàn tất',attention:'Cần chú ý',noSessions:'Chưa có ChatGPT Web đang mở',openFirst:'Mở một ChatGPT mới để Sentinel bắt đầu quan sát.',focus:'Mở tab',diagnose:'Chẩn đoán',queue:'Xếp lệnh',microscope:'Microscope',download:'Tải xuống',downloadAll:'Tải tất cả',noFiles:'Chưa phát hiện artifact thật.',noQueue:'Queue đang trống.',newRule:'Tạo automation',save:'Lưu',cancel:'Hủy',bridge:'Native AI Bridge',connected:'Đã kết nối',disconnected:'Chưa kết nối',language:'Ngôn ngữ',retention:'Lưu context',deep:'Deep Observe',recovery:'Tự phục hồi',handoff:'Tự handoff khi chạm giới hạn',watchdog:'Watchdog 30 giây',telemetry:'Chỉ telemetry',full:'Full visible context',off:'Không lưu',back:'Quay lại',timeline:'Timeline',health:'Sức khỏe',queuePrompt:'Prompt tiếp theo',addQueue:'Thêm vào Safe Queue',deleteContext:'Xóa Context Vault'},
  en:{controlRoom:'ChatGPT Control Room',openNew:'Open new ChatGPT',overview:'Overview',tasks:'Tasks',files:'Files',automation:'Automation',agentPort:'AI Port',settings:'Settings',sessions:'Sessions',working:'Working',completed:'Completed',attention:'Needs attention',noSessions:'No ChatGPT Web tabs are open',openFirst:'Open a ChatGPT tab to let Sentinel start observing.',focus:'Focus tab',diagnose:'Diagnose',queue:'Queue',microscope:'Microscope',download:'Download',downloadAll:'Download all',noFiles:'No verified artifacts detected.',noQueue:'Queue is empty.',newRule:'Create automation',save:'Save',cancel:'Cancel',bridge:'Native AI Bridge',connected:'Connected',disconnected:'Disconnected',language:'Language',retention:'Context retention',deep:'Deep Observe',recovery:'Auto recovery',handoff:'Auto handoff at conversation limit',watchdog:'30s watchdog',telemetry:'Telemetry only',full:'Full visible context',off:'Do not retain',back:'Back',timeline:'Timeline',health:'Health',queuePrompt:'Next prompt',addQueue:'Add to Safe Queue',deleteContext:'Delete Context Vault'}
};
const labels={vi:{DISCOVERED:'ĐÃ PHÁT HIỆN',IDLE:'SẴN SÀNG',COMPOSING:'ĐANG SOẠN',SUBMITTED:'ĐÃ GỬI',QUEUED:'ĐANG CHỜ',THINKING:'ĐANG SUY NGHĨ',DEEP_THINKING:'SUY NGHĨ SÂU',STREAMING:'ĐANG TRẢ LỜI',TOOL_RUNNING:'ĐANG DÙNG TOOL',WAITING_USER:'CHỜ NGƯỜI DÙNG',COMPLETING:'ĐANG HOÀN TẤT',COMPLETED:'HOÀN TẤT',CONNECTION_LOST:'MẤT KẾT NỐI',RATE_LIMITED:'GIỚI HẠN',CONVERSATION_LIMIT:'HẾT GIỚI HẠN CHAT',STALLED:'CÓ THỂ BỊ TREO',FAILED:'THẤT BẠI',DOM_DRIFT:'UI DRIFT'},en:{}};
for(const key of Object.keys(labels.vi))labels.en[key]=key.replaceAll('_',' ');
export const activeStates=new Set(['SUBMITTED','QUEUED','THINKING','DEEP_THINKING','STREAMING','TOOL_RUNNING','COMPLETING']);
export const alertStates=new Set(['CONNECTION_LOST','RATE_LIMITED','CONVERSATION_LIMIT','STALLED','FAILED','DOM_DRIFT']);
export const esc=(value)=>String(value??'').replace(/[&<>"']/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
export const locale=()=>ui.dashboard.settings?.locale==='en'?'en':'vi';
export const tr=(key)=>T[locale()][key]||T.vi[key]||key;
export const stateText=(state)=>labels[locale()][state]||state||'UNKNOWN';
export const fmtClock=(time)=>time?new Date(time).toLocaleTimeString(locale()==='vi'?'vi-VN':'en-US',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
export const fmtDuration=(start,end=Date.now())=>{if(!start)return '—';let s=Math.max(0,Math.floor((end-start)/1000));const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${m}:${String(sec).padStart(2,'0')}`;};
export const tone=(s)=>alertStates.has(s.state)?'error':s.state==='COMPLETED'?'complete':activeStates.has(s.state)?'running':'';
export const lamp=(s)=>alertStates.has(s.state)?'error':s.state==='COMPLETED'?'ok':activeStates.has(s.state)?'run':'';
export const taskBundle=(taskId)=>(ui.dashboard.tasks||[]).find((bundle)=>bundle?.task?.id===taskId)||null;

export async function command(name,params={}){const response=await chrome.runtime.sendMessage({type:'sentinel.commandRequest',command:name,params});if(!response?.ok)throw new Error(response?.error||'Sentinel command failed');return response.result;}
export function toast(message,error=false){const host=document.getElementById('toastHost'),node=document.createElement('div');node.className=`toast${error?' error':''}`;node.textContent=String(message);host.append(node);setTimeout(()=>node.remove(),3600);}
export function syncHeader(live=true){const chip=document.getElementById('monitorHealth');chip.classList.toggle('live',live);chip.querySelector('span').textContent=live?`${ui.dashboard.sessions.length} ChatGPT`:'Worker offline';document.getElementById('toggleDeep').setAttribute('aria-pressed',String(Boolean(ui.dashboard.settings?.deepObserve)));document.getElementById('togglePause').setAttribute('aria-pressed',String(Boolean(ui.dashboard.settings?.automationsEnabled&&!ui.dashboard.settings?.automationPaused)));document.getElementById('fileBadge').textContent=String(ui.dashboard.sessions.flatMap((s)=>s.artifacts||[]).filter((a)=>a.kind==='file').length);const taskBadge=document.getElementById('taskBadge');if(taskBadge)taskBadge.textContent=String((ui.dashboard.tasks||[]).length);document.documentElement.lang=locale();document.querySelectorAll('[data-i18n]').forEach((node)=>{const key=node.dataset.i18n;if(T[locale()][key])node.textContent=T[locale()][key];});}
